apiVersion: v1
entries:
  simply-dns-webhook:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2023-02-23T22:01:46.56491796+01:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: c6e0b2c00eb84a65fd78a47e0c3119ef03597534018789ee20d1c02a547d2866
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.1.3
    created: "2023-02-23T22:01:46.564712418+01:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: fe67f14159cdaab838f4d12e517163064cf698d4de3a5331eb46cb5dc32ef81f
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.1.3.tgz
    version: 1.1.3
  - apiVersion: v2
    appVersion: 1.1.2
    created: "2023-02-23T22:01:46.564507549+01:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 07e4ae8bbdc8fcfedcdf03ba835dc8f4a3c3b58226318f365b5802b3d81e8e82
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.1.2.tgz
    version: 1.1.2
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2023-02-23T22:01:46.564299792+01:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: ac102e2c99bdbc2cc4c2522043b729cd85783409b6876db33d42cb7dddbb1d18
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2023-02-23T22:01:46.564087347+01:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: f8957d73529e51e1acd498c0c89bdbe431f9de851fb9f0a6524253da560f597e
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2023-02-23T22:01:46.563861986+01:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 4e6498f38ca6a629c48570d4e8f764324506b4ca9b67c04a3aa5537f0c0ec343
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-02-23T22:01:46.56363733+01:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: cf3be17f6203ce9429c2646c5e674a1b23d9749094006f270b3fff19fb237a42
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-02-23T22:01:46.563415377+01:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 569f661f2eacc3fef309d407b772627319e45017e295545c66aa33d5b338e7d9
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-02-23T22:01:46.563180746+01:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 334532be5c3e14f9155ff0afaacfb8227a2e2589402c41b6d3fe262d26467fb4
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.0.tgz
    version: 1.0.0
generated: "2023-02-23T22:01:46.56273951+01:00"
