apiVersion: v1
entries:
  simply-dns-webhook:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-09-26T13:50:03.6985973+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 334532be5c3e14f9155ff0afaacfb8227a2e2589402c41b6d3fe262d26467fb4
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.0.tgz
    version: 1.0.0
generated: "2022-09-26T13:50:03.6975548+02:00"
