apiVersion: v1
entries:
  simply-dns-webhook:
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2022-10-15T20:44:44.8118968+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 4e6498f38ca6a629c48570d4e8f764324506b4ca9b67c04a3aa5537f0c0ec343
    icon: https://user-images.githubusercontent.com/51089137/195098737-fc66a30f-6174-45ed-b995-3f2689dafd2e.png
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-10-15T20:44:44.8118968+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: cf3be17f6203ce9429c2646c5e674a1b23d9749094006f270b3fff19fb237a42
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-10-15T20:44:44.8108776+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 569f661f2eacc3fef309d407b772627319e45017e295545c66aa33d5b338e7d9
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-10-15T20:44:44.8108776+02:00"
    description: A Helm chart for Simply.com dns01 challenge support for cert-manager.
      Refer to https://github.com/RunnerM/simply-dns-webhook for documentation.
    digest: 334532be5c3e14f9155ff0afaacfb8227a2e2589402c41b6d3fe262d26467fb4
    name: simply-dns-webhook
    type: application
    urls:
    - https://runnerm.github.io/simply-dns-webhook/simply-dns-webhook-1.0.0.tgz
    version: 1.0.0
generated: "2022-10-15T20:44:44.8083768+02:00"
